// ============================================================
// storage.js — LocalStorage seed data & persistence layer
// ============================================================

const DB = {
  destinations: 'ts_destinations',
  hotels: 'ts_hotels',
  packages: 'ts_packages',
  reviews: 'ts_reviews',
  bookings: 'ts_bookings',
  plans: 'ts_plans',
  theme: 'ts_theme',
  initialized: 'ts_initialized',
};

const SEED_DESTINATIONS = [
  { id:'d1', name:'Santorini', country:'Greece', continent:'Europe', image:'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80', rating:4.9, reviews:2841, priceRange:'$$$', minPrice:99600, season:['Spring','Summer'], adventureLevel:'Moderate', popularity:98, description:'Iconic white-washed cliffs, volcanic beaches, and blazing sunsets over the Aegean Sea.', tags:['Island','Romantic','Scenic'] },
  { id:'d2', name:'Kyoto', country:'Japan', continent:'Asia', image:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80', rating:4.8, reviews:3102, priceRange:'$$$', minPrice:116200, season:['Spring','Autumn'], adventureLevel:'Easy', popularity:96, description:'Ancient temples, bamboo groves, traditional tea houses, and cherry blossoms in spring.', tags:['Cultural','Historic','Nature'] },
  { id:'d3', name:'Machu Picchu', country:'Peru', continent:'South America', image:'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80', rating:4.9, reviews:1987, priceRange:'$$', minPrice:74700, season:['Spring','Autumn'], adventureLevel:'Challenging', popularity:97, description:'Mystical Incan citadel perched high in the Andes, shrouded in cloud and wonder.', tags:['Adventure','Historic','UNESCO'] },
  { id:'d4', name:'Maldives', country:'Maldives', continent:'Asia', image:'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80', rating:4.9, reviews:2234, priceRange:'$$$$', minPrice:207500, season:['Winter','Spring'], adventureLevel:'Easy', popularity:99, description:'Crystal-clear lagoons, overwater bungalows, and coral reefs teeming with marine life.', tags:['Beach','Luxury','Diving'] },
  { id:'d5', name:'Amalfi Coast', country:'Italy', continent:'Europe', image:'https://images.unsplash.com/photo-1612698093158-e07ac200d44e?w=800&q=80', rating:4.7, reviews:1876, priceRange:'$$$', minPrice:91300, season:['Summer','Spring'], adventureLevel:'Easy', popularity:94, description:'Dramatic cliffside villages, turquoise water, lemon groves, and world-class Italian cuisine.', tags:['Scenic','Romantic','Food'] },
  { id:'d6', name:'Safari Serengeti', country:'Tanzania', continent:'Africa', image:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', rating:4.8, reviews:1432, priceRange:'$$$$', minPrice:265600, season:['Summer','Winter'], adventureLevel:'Moderate', popularity:91, description:'Witness the Great Migration across endless golden plains teeming with wildlife.', tags:['Safari','Wildlife','Adventure'] },
  { id:'d7', name:'Bali', country:'Indonesia', continent:'Asia', image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80', rating:4.7, reviews:3876, priceRange:'$$', minPrice:58100, season:['Spring','Summer'], adventureLevel:'Easy', popularity:95, description:'Lush rice terraces, spiritual temples, surf breaks, and vibrant arts scene.', tags:['Beach','Cultural','Wellness'] },
  { id:'d8', name:'Patagonia', country:'Argentina', continent:'South America', image:'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80', rating:4.8, reviews:987, priceRange:'$$$', minPrice:149400, season:['Summer'], adventureLevel:'Extreme', popularity:88, description:'Jagged granite peaks, ancient glaciers, and untamed wilderness at the end of the world.', tags:['Adventure','Hiking','Nature'] },
  { id:'d9', name:'Prague', country:'Czech Republic', continent:'Europe', image:'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80', rating:4.6, reviews:2654, priceRange:'$$', minPrice:49800, season:['Spring','Autumn','Winter'], adventureLevel:'Easy', popularity:93, description:'Gothic spires, cobblestone lanes, medieval castles, and legendary Czech beer culture.', tags:['Historic','Cultural','Nightlife'] },
  { id:'d10', name:'Queenstown', country:'New Zealand', continent:'Oceania', image:'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80', rating:4.8, reviews:1654, priceRange:'$$$', minPrice:132800, season:['Summer','Winter'], adventureLevel:'Extreme', popularity:90, description:'Adventure capital of the world — bungee jumping, skiing, and fjord scenery.', tags:['Adventure','Skiing','Scenic'] },
  { id:'d11', name:'Marrakech', country:'Morocco', continent:'Africa', image:'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80', rating:4.5, reviews:2109, priceRange:'$$', minPrice:45650, season:['Spring','Autumn'], adventureLevel:'Easy', popularity:89, description:'Vibrant souks, fragrant spice markets, ornate palaces, and the mystical Medina.', tags:['Cultural','Food','Architecture'] },
  { id:'d12', name:'Iceland', country:'Iceland', continent:'Europe', image:'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&q=80', rating:4.9, reviews:1543, priceRange:'$$$$', minPrice:182600, season:['Summer','Winter'], adventureLevel:'Challenging', popularity:92, description:'Northern lights, geysers, black sand beaches, and midnight sun.', tags:['Nature','Adventure','Unique'] },
  { id:'d13', name:'Bangkok', country:'Thailand', continent:'Asia', image:'https://images.unsplash.com/photo-1508009603885-50cf7c8dd0d5?w=800&q=80', rating:4.5, reviews:3421, priceRange:'$', minPrice:33200, season:['Winter','Spring'], adventureLevel:'Easy', popularity:94, description:'Gleaming temples, street food paradise, bustling markets, and electric nightlife.', tags:['Food','Cultural','Nightlife'] },
  { id:'d14', name:'Dubrovnik', country:'Croatia', continent:'Europe', image:'https://images.unsplash.com/photo-1555990793-da11153b6ca7?w=800&q=80', rating:4.7, reviews:1876, priceRange:'$$$', minPrice:83000, season:['Summer','Spring'], adventureLevel:'Easy', popularity:91, description:'Pearl of the Adriatic with medieval city walls, crystal sea, and island hopping.', tags:['Scenic','Historic','Beach'] },
  { id:'d15', name:'New York City', country:'USA', continent:'North America', image:'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80', rating:4.6, reviews:5432, priceRange:'$$$$', minPrice:166000, season:['Spring','Autumn','Winter'], adventureLevel:'Easy', popularity:99, description:'The city that never sleeps — iconic skyline, world-class culture, food, and energy.', tags:['Urban','Food','Culture'] },
  { id:'d16', name:'Cape Town', country:'South Africa', continent:'Africa', image:'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80', rating:4.7, reviews:1987, priceRange:'$$', minPrice:70550, season:['Summer','Spring'], adventureLevel:'Moderate', popularity:87, description:'Table Mountain, Cape Winelands, penguin colonies, and breathtaking ocean drives.', tags:['Nature','Wine','Adventure'] },
  { id:'d17', name:'Phuket', country:'Thailand', continent:'Asia', image:'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&q=80', rating:4.5, reviews:2876, priceRange:'$$', minPrice:53950, season:['Winter','Spring'], adventureLevel:'Easy', popularity:93, description:'Tropical beaches, limestone karsts, vibrant nightlife, and clear emerald waters.', tags:['Beach','Nightlife','Island'] },
  { id:'d18', name:'Swiss Alps', country:'Switzerland', continent:'Europe', image:'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80', rating:4.9, reviews:1432, priceRange:'$$$$', minPrice:232400, season:['Winter','Summer'], adventureLevel:'Challenging', popularity:95, description:'Towering peaks, pristine ski slopes, charming alpine villages, and luxury chalets.', tags:['Skiing','Nature','Luxury'] },
  { id:'d19', name:'Rio de Janeiro', country:'Brazil', continent:'South America', image:'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80', rating:4.5, reviews:2543, priceRange:'$$', minPrice:62250, season:['Summer','Spring'], adventureLevel:'Moderate', popularity:90, description:'Christ the Redeemer, Copacabana Beach, carnival spirit, and samba rhythm.', tags:['Beach','Culture','Nightlife'] },
  { id:'d20', name:'Petra', country:'Jordan', continent:'Asia', image:'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800&q=80', rating:4.8, reviews:1234, priceRange:'$$', minPrice:66400, season:['Spring','Autumn'], adventureLevel:'Moderate', popularity:86, description:'The Rose City carved from rose-red cliffs — a Nabataean wonder of the ancient world.', tags:['Historic','UNESCO','Adventure'] },
];

const SEED_HOTELS = [
  { id:'h1', name:'Oia Sunset Villas', destination:'Santorini', country:'Greece', image:'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80', rating:4.9, reviews:876, pricePerNight:34860, category:'Luxury', amenities:['Pool','Spa','WiFi','Restaurant','Bar','Concierge'], description:'Clifftop luxury suites with private plunge pools and unobstructed caldera views.', available:true, rooms:['Deluxe Suite','Caldera View Room','Presidential Villa'] },
  { id:'h2', name:'Kyoto Machiya Inn', destination:'Kyoto', country:'Japan', image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80', rating:4.8, reviews:654, pricePerNight:23240, category:'Boutique', amenities:['WiFi','Garden','Tea Ceremony','Onsen','Breakfast'], description:'Restored 200-year-old wooden townhouse in the historic Gion district.', available:true, rooms:['Traditional Tatami','Garden View Room','Premium Suite'] },
  { id:'h3', name:'Inkaterra Machu Picchu', destination:'Machu Picchu', country:'Peru', image:'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80', rating:4.7, reviews:432, pricePerNight:29050, category:'Eco-Luxury', amenities:['WiFi','Restaurant','Spa','Nature Tours','Breakfast'], description:'Cloud forest sanctuary steps from the citadel with organic garden and birdwatching.', available:true, rooms:['Deluxe Room','Junior Suite','Cloud Forest Suite'] },
  { id:'h4', name:'Conrad Maldives Rangali', destination:'Maldives', country:'Maldives', image:'https://images.unsplash.com/photo-1439130490301-25e322d88054?w=800&q=80', rating:5.0, reviews:1243, pricePerNight:99600, category:'Ultra-Luxury', amenities:['Overwater Bungalow','Diving','Spa','Multiple Restaurants','Butler','Pool'], description:'Iconic overwater villas above a coral lagoon with glass-floor underwater restaurant.', available:true, rooms:['Water Villa','Reef Water Suite','Two-Bedroom Water Retreat'] },
  { id:'h5', name:'Villa Cimbrone', destination:'Amalfi Coast', country:'Italy', image:'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80', rating:4.8, reviews:567, pricePerNight:39840, category:'Luxury', amenities:['Pool','Garden','Restaurant','WiFi','Spa','Terrace'], description:'Medieval villa turned hotel with legendary Terrace of Infinity overlooking the coast.', available:false, rooms:['Classic Room','Deluxe Sea View','Suite with Terrace'] },
  { id:'h6', name:'Four Seasons Safari Lodge', destination:'Safari Serengeti', country:'Tanzania', image:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', rating:4.9, reviews:389, pricePerNight:73870, category:'Safari-Luxury', amenities:['Game Drives','Pool','Spa','Restaurant','Bar','WiFi'], description:'Intimate lodge on the rim of Serengeti with resident wildlife crossing the grounds.', available:true, rooms:['Safari Suite','Family Suite','Presidential Tent'] },
  { id:'h7', name:'Alaya Resort Ubud', destination:'Bali', country:'Indonesia', image:'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80', rating:4.7, reviews:876, pricePerNight:18260, category:'Boutique', amenities:['Infinity Pool','Spa','Yoga','Restaurant','WiFi','Rice Field Views'], description:'Tranquil rice-terrace resort with daily yoga, Balinese spa treatments, and cooking classes.', available:true, rooms:['Pool Villa','Rice Field Suite','Treehouse Room'] },
  { id:'h8', name:'EcoCamp Patagonia', destination:'Patagonia', country:'Argentina', image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80', rating:4.6, reviews:298, pricePerNight:25730, category:'Eco', amenities:['Trekking','Restaurant','Bar','Guided Tours','WiFi'], description:'Geodesic dome camp beneath Torres del Paine with panoramic mountain views.', available:true, rooms:['Standard Dome','Suite Dome','Premium Dome'] },
  { id:'h9', name:'Augustine Hotel Prague', destination:'Prague', country:'Czech Republic', image:'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', rating:4.7, reviews:1102, pricePerNight:16185, category:'Heritage', amenities:['Restaurant','Bar','Spa','WiFi','Fitness','Courtyard'], description:'13th-century monastery converted to a luxury hotel in the Malá Strana quarter.', available:true, rooms:['Classic Room','Executive Room','Monastery Suite'] },
  { id:'h10', name:"Eichardt's Private Hotel", destination:'Queenstown', country:'New Zealand', image:'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80', rating:4.9, reviews:432, pricePerNight:46480, category:'Luxury', amenities:['Lakefront','Bar','Concierge','WiFi','Fireplace','Boat Charter'], description:'Historic lakefront manor with a private jetty on Lake Wakatipu.', available:true, rooms:['Lakefront Suite','Penthouse','Apartment Suite'] },
  { id:'h11', name:'La Mamounia', destination:'Marrakech', country:'Morocco', image:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80', rating:4.8, reviews:1567, pricePerNight:31540, category:'Palace', amenities:['Pool','Spa','Multiple Restaurants','Casino','Gardens','WiFi'], description:'Legendary palace hotel surrounded by gardens and Moroccan craftsmanship.', available:true, rooms:['Classic Room','Riad Suite','Garden Pavilion'] },
  { id:'h12', name:'Ion Adventure Hotel', destination:'Iceland', country:'Iceland', image:'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80', rating:4.7, reviews:543, pricePerNight:26560, category:'Design', amenities:['Northern Lights Viewing','Geothermal Pool','Restaurant','Bar','WiFi'], description:'Architecturally striking eco hotel beside a lava field with geothermal pools.', available:true, rooms:['Standard Room','Aurora Suite','Premium Loft'] },
  { id:'h13', name:'Capella Bangkok', destination:'Bangkok', country:'Thailand', image:'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80', rating:4.9, reviews:765, pricePerNight:39840, category:'Luxury', amenities:['Riverside','Pool','Spa','Multiple Restaurants','Butler','WiFi'], description:'Graceful riverside retreat blending Thai arts with modern luxury along the Chao Phraya.', available:true, rooms:['Deluxe Room','River View Suite','Riverside Villa'] },
  { id:'h14', name:'Hotel Excelsior Dubrovnik', destination:'Dubrovnik', country:'Croatia', image:'https://images.unsplash.com/photo-1529290130-4ca3753253ae?w=800&q=80', rating:4.6, reviews:897, pricePerNight:24070, category:'Classic', amenities:['Pool','Beach Access','Restaurant','Bar','WiFi','Spa'], description:'Grand 1913 hotel with a private beach and views of the medieval Old Town.', available:true, rooms:['Sea View Room','Junior Suite','Presidential Suite'] },
  { id:'h15', name:'The Plaza New York', destination:'New York City', country:'USA', image:'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=800&q=80', rating:4.8, reviews:2341, pricePerNight:53950, category:'Iconic', amenities:['Spa','Multiple Restaurants','Bar','Fitness','Concierge','WiFi'], description:'Iconic landmark hotel at Fifth Avenue with Central Park views since 1907.', available:true, rooms:['Deluxe Room','Park View Suite','Grand Suite'] },
  { id:'h16', name:'Ellerman House', destination:'Cape Town', country:'South Africa', image:'https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=800&q=80', rating:4.8, reviews:432, pricePerNight:34030, category:'Boutique', amenities:['Pool','Vineyard','Spa','Restaurant','Art Gallery','WiFi'], description:'Clifftop Victorian villa with an art collection, wine cellar, and Atlantic Ocean views.', available:true, rooms:['Classic Room','Suite','Villa'] },
  { id:'h17', name:'Trisara Phuket', destination:'Phuket', country:'Thailand', image:'https://images.unsplash.com/photo-1540541338537-71acdbdeae2c?w=800&q=80', rating:4.9, reviews:678, pricePerNight:45650, category:'Luxury', amenities:['Private Pool','Beach','Spa','Restaurant','Snorkeling','WiFi'], description:'Private ocean-front pool villas in a secluded bay with immaculate service.', available:true, rooms:['Ocean Pool Villa','Residence','Royal Ocean Pool Villa'] },
  { id:'h18', name:'The Chedi Andermatt', destination:'Swiss Alps', country:'Switzerland', image:'https://images.unsplash.com/photo-1549294413-26f195200c16?w=800&q=80', rating:4.9, reviews:876, pricePerNight:59760, category:'Alpine-Luxury', amenities:['Ski-In/Out','Spa','Pool','Restaurant','Bar','Fireplace'], description:'Asian-influenced alpine sanctuary with a 35-metre indoor pool and ski-in access.', available:true, rooms:['Deluxe Room','Mountain Suite','Grand Suite'] },
  { id:'h19', name:'Copacabana Palace', destination:'Rio de Janeiro', country:'Brazil', image:'https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80', rating:4.7, reviews:1234, pricePerNight:29880, category:'Classic', amenities:['Pool','Spa','Restaurant','Bar','WiFi','Beach Access'], description:"Belle Époque icon on Copacabana beachfront — Rio's most storied address since 1923.", available:true, rooms:['Standard Room','Luxury Room','Junior Suite'] },
  { id:'h20', name:'Kempinski Hotel Ishtar', destination:'Petra', country:'Jordan', image:'https://images.unsplash.com/photo-1531088009183-5ff5b7c95f91?w=800&q=80', rating:4.6, reviews:543, pricePerNight:24070, category:'Resort', amenities:['Multiple Pools','Spa','Restaurant','WiFi','Dead Sea Access','Tennis'], description:"Palatial resort with private beach on the Dead Sea near Petra's ancient wonders.", available:true, rooms:['Dead Sea View Room','Suite','Royal Suite'] },
];

const SEED_PACKAGES = [
  { id:'p1', name:'Greek Island Odyssey', destination:'Santorini', duration:8, price:239870, rating:4.9, reviews:342, image:'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80', transport:'Flight', hotelCategory:'Luxury', included:['Flights','4-Star Hotel','Daily Breakfast','Island Tour','Wine Tasting','Sunset Cruise'], highlights:'Fira walking tour, Oia sunset, Akrotiri ruins, catamaran trip', type:'Romantic' },
  { id:'p2', name:'Japan Cherry Blossom Trail', destination:'Kyoto', duration:10, price:265600, rating:4.9, reviews:287, image:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80', transport:'Flight', hotelCategory:'Boutique', included:['Flights','Ryokan Stay','Breakfast & Dinner','JR Pass','Tea Ceremony','Temple Tour'], highlights:'Arashiyama Bamboo, Fushimi Inari, Nishiki Market, Geisha district', type:'Cultural' },
  { id:'p3', name:'Inca Trail Adventure', destination:'Machu Picchu', duration:7, price:156870, rating:4.8, reviews:198, image:'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80', transport:'Flight+Train', hotelCategory:'Boutique', included:['Flights','Hotel','Breakfast','Guided Inca Trek','Cusco Tour','Entry Fees'], highlights:'Inca Trail hike, Sun Gate sunrise, Cusco Old Town, Sacred Valley', type:'Adventure' },
  { id:'p4', name:'Maldives Paradise Escape', destination:'Maldives', duration:6, price:373500, rating:5.0, reviews:412, image:'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80', transport:'Flight+Seaplane', hotelCategory:'Ultra-Luxury', included:['Flights','Overwater Villa','All-Inclusive','Snorkeling','Diving','Spa Credit'], highlights:'Private overwater villa, coral reef diving, dolphin cruise, sunset fishing', type:'Luxury' },
  { id:'p5', name:'Amalfi & Cinque Terre', destination:'Amalfi Coast', duration:9, price:215800, rating:4.7, reviews:231, image:'https://images.unsplash.com/photo-1612698093158-e07ac200d44e?w=800&q=80', transport:'Flight', hotelCategory:'Luxury', included:['Flights','Boutique Hotel','Breakfast','Boat Tour','Wine Tour','Cooking Class'], highlights:'Positano village, Ravello gardens, Cinque Terre hike, local limoncello', type:'Cultural' },
  { id:'p6', name:'Serengeti Migration Safari', destination:'Safari Serengeti', duration:10, price:481400, rating:4.9, reviews:156, image:'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', transport:'Flight+Charter', hotelCategory:'Safari-Luxury', included:['Flights','Lodge','All-Inclusive','Game Drives','Bush Walk','Balloon Safari'], highlights:'Great Migration, Big Five, Maasai village, Ngorongoro Crater', type:'Adventure' },
  { id:'p7', name:'Bali Wellness Retreat', destination:'Bali', duration:8, price:136950, rating:4.7, reviews:543, image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80', transport:'Flight', hotelCategory:'Boutique', included:['Flights','Villa','Breakfast','Daily Yoga','Spa Treatments','Temple Tour'], highlights:'Ubud monkey forest, Tegallalang rice terraces, Uluwatu sunset, cooking class', type:'Wellness' },
  { id:'p8', name:'Patagonia Trekking Expedition', destination:'Patagonia', duration:12, price:323700, rating:4.8, reviews:123, image:'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80', transport:'Flight', hotelCategory:'Eco', included:['Flights','Eco Camp','All-Inclusive','W Trek','Glacier Walk','Boat Trip'], highlights:'Torres del Paine trek, Grey Glacier, Perito Moreno, condor spotting', type:'Adventure' },
  { id:'p9', name:'Prague & Budapest Discovery', destination:'Prague', duration:7, price:120350, rating:4.6, reviews:378, image:'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80', transport:'Flight', hotelCategory:'Heritage', included:['Flights','Hotel','Breakfast','City Tours','Beer Tasting','River Cruise'], highlights:'Prague Castle, Charles Bridge, Budapest thermal baths, Ruin bars', type:'Cultural' },
  { id:'p10', name:'New Zealand Adventure Rush', destination:'Queenstown', duration:9, price:282200, rating:4.8, reviews:267, image:'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80', transport:'Flight', hotelCategory:'Luxury', included:['Flights','Hotel','Breakfast','Bungee Jump','Skydive','Milford Sound'], highlights:'Bungee jumping, skydiving, Milford Sound cruise, Lord of the Rings tour', type:'Adventure' },
  { id:'p11', name:'Morocco Desert Magic', destination:'Marrakech', duration:8, price:145250, rating:4.5, reviews:289, image:'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80', transport:'Flight', hotelCategory:'Palace', included:['Flights','Riad Stay','Breakfast','Sahara Tour','Camel Trek','Hammam'], highlights:'Medina souks, Sahara dunes, Camel trek, Atlas Mountains, Fes Medina', type:'Cultural' },
  { id:'p12', name:'Iceland Northern Lights', destination:'Iceland', duration:7, price:257300, rating:4.9, reviews:198, image:'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&q=80', transport:'Flight', hotelCategory:'Design', included:['Flights','Hotel','Breakfast','Northern Lights Tour','Golden Circle','Blue Lagoon'], highlights:'Northern Lights, Geysir, Gullfoss waterfall, Black sand beach, Ice cave', type:'Nature' },
  { id:'p13', name:'Thailand Island Hopper', destination:'Phuket', duration:10, price:164340, rating:4.5, reviews:456, image:'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&q=80', transport:'Flight', hotelCategory:'Luxury', included:['Flights','Resort','Breakfast','Island Hopping','Cooking Class','Elephant Sanctuary'], highlights:'Phi Phi Islands, James Bond Island, Phang Nga Bay, street food tour', type:'Beach' },
  { id:'p14', name:'Dubrovnik & Split Coastal', destination:'Dubrovnik', duration:8, price:182600, rating:4.7, reviews:312, image:'https://images.unsplash.com/photo-1555990793-da11153b6ca7?w=800&q=80', transport:'Flight', hotelCategory:'Classic', included:['Flights','Hotel','Breakfast','Wall Walk','Island Tour','Wine Tasting'], highlights:'City Walls walk, Game of Thrones tour, Hvar island, Diocletian Palace', type:'Cultural' },
  { id:'p15', name:'New York City Break', destination:'New York City', duration:5, price:199200, rating:4.6, reviews:876, image:'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80', transport:'Flight', hotelCategory:'Iconic', included:['Flights','Hotel','Broadway Show','NY Pass','Helicopter Tour','Food Tour'], highlights:'Times Square, Central Park, Brooklyn Bridge, Met Museum, Empire State', type:'Urban' },
  { id:'p16', name:'Cape Town & Safari Combo', destination:'Cape Town', duration:11, price:315400, rating:4.7, reviews:198, image:'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80', transport:'Flight', hotelCategory:'Boutique', included:['Flights','Hotel','Breakfast','Table Mountain','Winelands Tour','Kruger Safari'], highlights:'Table Mountain, Cape Point, Boulders Beach penguins, Stellenbosch wine', type:'Adventure' },
  { id:'p17', name:'Swiss Alps Winter Escape', destination:'Swiss Alps', duration:7, price:348600, rating:4.9, reviews:234, image:'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80', transport:'Flight+Train', hotelCategory:'Alpine-Luxury', included:['Flights','Chalet','Half Board','Ski Pass','Equipment','Spa Access'], highlights:'Jungfrau, Zermatt, Matterhorn views, Verbier ski, Fondue evenings', type:'Skiing' },
  { id:'p18', name:'Rio Carnival Experience', destination:'Rio de Janeiro', duration:6, price:174300, rating:4.5, reviews:312, image:'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80', transport:'Flight', hotelCategory:'Classic', included:['Flights','Hotel','Breakfast','Carnival Tickets','Sugarloaf','City Tour'], highlights:'Carnival parade, Christ the Redeemer, Sugarloaf, Copacabana, Samba show', type:'Cultural' },
  { id:'p19', name:'Jordan Ancient Wonders', destination:'Petra', duration:7, price:157700, rating:4.8, reviews:176, image:'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800&q=80', transport:'Flight', hotelCategory:'Resort', included:['Flights','Hotel','Breakfast','Petra Tour','Wadi Rum','Dead Sea','Jerash'], highlights:'Treasury at Petra, Wadi Rum jeep tour, Dead Sea float, Roman Jerash', type:'Historic' },
  { id:'p20', name:'Bangkok & Chiang Mai Discovery', destination:'Bangkok', duration:9, price:128650, rating:4.5, reviews:543, image:'https://images.unsplash.com/photo-1508009603885-50cf7c8dd0d5?w=800&q=80', transport:'Flight', hotelCategory:'Luxury', included:['Flights','Hotel','Breakfast','Temple Tour','Night Market','Cooking Class','Elephant Care'], highlights:'Grand Palace, Doi Suthep temple, Night Bazaar, floating market, Thai massage', type:'Cultural' },
];

const SEED_REVIEWS = [
  { id:'r1', destinationId:'d1', hotelId:'h1', userName:'Sarah Mitchell', avatar:'SM', rating:5, title:'Best vacation of my life', body:"Santorini exceeded every expectation. The sunsets from Oia are genuinely breathtaking — no filter needed. Our villa had a private plunge pool and the staff arranged everything perfectly. Already planning our return.", date:'2024-11-15', helpful:124, verified:true },
  { id:'r2', destinationId:'d2', hotelId:'h2', userName:'James Thornton', avatar:'JT', rating:5, title:'Japan is magical in spring', body:"The cherry blossoms along the Philosopher's Path were unlike anything I've ever seen. The Machiya Inn staff spoke minimal English but communicated everything through warmth and generosity. The onsen at midnight was transcendent.", date:'2024-10-22', helpful:98, verified:true },
  { id:'r3', destinationId:'d7', hotelId:'h7', userName:'Priya Sharma', avatar:'PS', rating:5, title:'Bali healed my soul', body:'I came stressed and left transformed. The yoga sessions at sunrise overlooking rice paddies, the temple ceremonies, the Balinese massages — Bali operates on a different frequency. Alaya Resort is worth every penny.', date:'2024-11-03', helpful:87, verified:true },
  { id:'r4', destinationId:'d4', hotelId:'h4', userName:'Michael Chen', avatar:'MC', rating:5, title:'Worth every dollar', body:'The Maldives is genuinely paradise. We stayed in an overwater villa and woke up to turquoise water every morning. The underwater restaurant dinner was the most surreal meal I ever had.', date:'2024-09-18', helpful:203, verified:true },
  { id:'r5', destinationId:'d6', hotelId:'h6', userName:'Emma Johansson', avatar:'EJ', rating:5, title:'Safari changed my perspective', body:'Watching 10,000 wildebeest cross the Mara River while sipping coffee at dawn is something I will never forget. The Four Seasons lodge blends luxury with wilderness seamlessly. Our guide David was exceptional.', date:'2024-08-30', helpful:156, verified:true },
  { id:'r6', destinationId:'d12', hotelId:'h12', userName:'Luca Bianchi', avatar:'LB', rating:5, title:'Northern Lights are real magic', body:"We saw the aurora four nights in a row from our hotel's outdoor hot tub. Iceland in winter is otherworldly — black sand beaches, frozen waterfalls, and that geothermal silence. The Ion Hotel design is stunning.", date:'2024-12-01', helpful:178, verified:true },
  { id:'r7', destinationId:'d3', hotelId:'h3', userName:'Ana Ramirez', avatar:'AR', rating:4, title:'Incredibly moving experience', body:'Hiking the Inca Trail at 4am to reach Sun Gate at sunrise with Machu Picchu emerging from the mist below — I cried. The altitude was tough and the trek demanding but every step was worth it. Book guides early!', date:'2024-10-08', helpful:134, verified:true },
  { id:'r8', destinationId:'d8', hotelId:'h8', userName:'Tom Wakefield', avatar:'TW', rating:5, title:'Patagonia is raw and perfect', body:'The Torres del Paine W trek was the most physically demanding and visually rewarding week of my life. Sleeping in the EcoCamp domes with the stars visible through the skylight and glaciers outside — extraordinary.', date:'2024-01-20', helpful:89, verified:true },
  { id:'r9', destinationId:'d11', hotelId:'h11', userName:'Fatima Al-Hassan', avatar:'FA', rating:5, title:'Marrakech is a sensory feast', body:'La Mamounia is a palace in every sense. The Medina is chaotic and wonderful — I got lost for hours in the souks and loved every moment. The hammam at the hotel should be mandatory. Moroccan cuisine is unreal.', date:'2024-11-28', helpful:112, verified:true },
  { id:'r10', destinationId:'d18', hotelId:'h18', userName:'David Park', avatar:'DP', rating:5, title:'Swiss Alps skiing is flawless', body:'The powder at Andermatt was waist-deep after a storm and we had the runs almost to ourselves. Chedi hotel is ridiculous — the 35m pool, the ski-in access, the raclette dinners. Switzerland delivers absolutely everything it promises.', date:'2024-02-14', helpful:145, verified:true },
  { id:'r11', destinationId:'d5', hotelId:'h5', userName:'Claire Dupont', avatar:'CD', rating:5, title:'Amalfi is pure romance', body:'We rented a vespa and drove the Amalfi Drive at golden hour. The towns clinging to cliffs, the lemon groves, the coastal seafood — Italy does everything better. Villa Cimbrone terrace at sunset made us both emotional.', date:'2024-07-12', helpful:167, verified:true },
  { id:'r12', destinationId:'d9', hotelId:'h9', userName:'Boris Novak', avatar:'BN', rating:4, title:'Prague is a fairy tale city', body:"The Augustine in Malá Strana is the best hotel I've stayed at in Europe. Prague castle at dusk, the Charles Bridge at dawn before the crowds, absinth bars and the best goulash I've tasted.", date:'2024-09-05', helpful:78, verified:true },
  { id:'r13', destinationId:'d10', hotelId:'h10', userName:'Katie Williams', avatar:'KW', rating:5, title:'Queenstown is adrenaline heaven', body:"Bungee jumped off the Kawarau Bridge (terrifying), skydived over Lake Wakatipu (life-changing), and sailed Milford Sound (humbling). Eichardt's hotel is the perfect luxury base.", date:'2024-03-19', helpful:198, verified:true },
  { id:'r14', destinationId:'d13', hotelId:'h13', userName:'Raj Patel', avatar:'RP', rating:4, title:'Bangkok overwhelms in the best way', body:'The temples, the street food, the tuk-tuks, the night markets — Bangkok is chaos and magic simultaneously. Capella Hotel on the river was a peaceful sanctuary after the city noise.', date:'2024-10-15', helpful:91, verified:true },
  { id:'r15', destinationId:'d14', hotelId:'h14', userName:'Sophie Laurent', avatar:'SL', rating:5, title:'Dubrovnik is the perfect summer city', body:'Walking the city walls at 7am before the crowds with the Adriatic shimmering below was worth waking up early every day. The island hop to Lokrum and Hvar was magical.', date:'2024-07-28', helpful:143, verified:true },
  { id:'r16', destinationId:'d15', hotelId:'h15', userName:'Marcus Johnson', avatar:'MJ', rating:4, title:'NYC energy is unlike anywhere', body:'The Plaza exceeded expectations — impeccably maintained and the location on 5th Avenue is unbeatable. Central Park runs, Broadway shows, the High Line, Michelin star dinners.', date:'2024-11-20', helpful:87, verified:true },
  { id:'r17', destinationId:'d16', hotelId:'h16', userName:'Amelia Scott', avatar:'AS', rating:5, title:'Cape Town stole my heart', body:'Table Mountain was in cloud when we arrived and cleared perfectly for our cable car ride — worth the wait. Ellerman House wine selection was world class. Penguin colony at Boulders Beach is absurdly adorable.', date:'2024-04-10', helpful:112, verified:true },
  { id:'r18', destinationId:'d17', hotelId:'h17', userName:'Kevin Tanaka', avatar:'KT', rating:4, title:'Phuket has something for everyone', body:'Trisara resort kept us at the villa for the first two days — the private pool and ocean views were hypnotic. Eventually explored Phi Phi by longtail boat and snorkeled with reef sharks.', date:'2024-05-22', helpful:76, verified:true },
  { id:'r19', destinationId:'d19', hotelId:'h19', userName:'Isabella Ferreira', avatar:'IF', rating:4, title:'Rio is vibrant and beautiful', body:"Cristo Redentor at dawn with low cloud swirling around the statue is a genuinely powerful experience. Copacabana Palace is old-world glamour done right — the pool scene is very much a scene.", date:'2024-02-28', helpful:89, verified:true },
  { id:'r20', destinationId:'d20', hotelId:'h20', userName:'Oliver Hughes', avatar:'OH', rating:5, title:'Petra is ancient and awesome', body:'Walking through the Siq canyon as it narrows and the Treasury reveals itself in rose-red stone is breathtaking. Petra by Night (candles illuminating the entire path) should not be missed.', date:'2024-08-15', helpful:134, verified:true },
  { id:'r21', destinationId:'d1', hotelId:null, userName:'Rachel Green', avatar:'RG', rating:5, title:'Oia is worth the hype', body:'Arrived skeptical about Santorini being overhyped. Left completely converted. Go in shoulder season (May/October) to avoid peak crowds. The blue dome churches and caldera views delivered everything promised.', date:'2024-10-20', helpful:156, verified:false },
  { id:'r22', destinationId:'d2', hotelId:null, userName:'Thomas Berg', avatar:'TB', rating:5, title:'Autumn Kyoto is perfection', body:'Maple leaves in Arashiyama in November — deep reds and oranges reflected in the ponds at Tenryu-ji. The tea ceremony was meditative. Every ramen shop, every temple garden, every ryokan breakfast. Japan is meticulous.', date:'2024-11-10', helpful:98, verified:false },
  { id:'r23', destinationId:'d7', hotelId:null, userName:'Nina Torres', avatar:'NT', rating:4, title:'Bali for digital nomads', body:"Canggu is the best place I've ever worked remotely — fast WiFi, great coffee, surfing at 6am, yoga at 7am, laptop by the pool by 9am. Ubud is more spiritual and cultural. Bali has ruined normal life for me.", date:'2024-11-25', helpful:67, verified:false },
  { id:'r24', destinationId:'d12', hotelId:null, userName:'Hans Weber', avatar:'HW', rating:5, title:'Iceland in December is otherworldly', body:'Complete darkness by 4pm and yet the most dramatic landscapes on earth. Driving the Ring Road, stopping at every waterfall, steam rising from geothermal vents, volcanic craters — Iceland makes you feel small and alive.', date:'2024-12-08', helpful:112, verified:false },
  { id:'r25', destinationId:'d18', hotelId:null, userName:'Mei Lin', avatar:'ML', rating:5, title:'Switzerland: expensive but worth it', body:'Yes, the CHF is brutal. A sandwich costs what a meal costs in Thailand. And yet Switzerland gives you the Matterhorn, precision trains, fondue by the fire, and ski runs so perfectly groomed they seem artificial. Worth it entirely.', date:'2024-02-20', helpful:89, verified:false },
  { id:'r26', destinationId:'d4', hotelId:null, userName:'Alex Chen', avatar:'AC', rating:5, title:'Maldives — stop questioning it', body:"I kept asking if it was 'worth it.' Yes. Unambiguously. We snorkeled with manta rays outside our bungalow door. The water is 29°C and so clear you can see the reef from your deck. Book once in your life.", date:'2024-09-28', helpful:201, verified:false },
  { id:'r27', destinationId:'d5', hotelId:null, userName:'Marco Rossi', avatar:'MR', rating:4, title:'Amalfi Coast best in spring', body:'June is already crowded. Go in late April or May — blooming citrus, fewer tourists, the sea still quiet. Ravello festival, limoncello tastings, ancient Greek temples at Paestum nearby. Southern Italy is living history.', date:'2024-05-18', helpful:78, verified:false },
  { id:'r28', destinationId:'d6', hotelId:null, userName:'Zara Williams', avatar:'ZW', rating:5, title:'Africa changes you', body:'The first morning game drive, watching elephants move silently through the acacia trees at dawn, a lioness teaching cubs to hunt — no wildlife documentary prepares you for the real thing. Africa gets under your skin permanently.', date:'2024-09-02', helpful:189, verified:false },
  { id:'r29', destinationId:'d9', hotelId:null, userName:'Petra Novak', avatar:'PN', rating:4, title:'Prague is astonishingly beautiful', body:"The city's medieval core is so intact it feels like a film set. Prague Castle, Josefov, the Art Nouveau Municipal House — genuinely world-class architecture at every turn. Visit in December for the Christmas markets.", date:'2024-12-03', helpful:67, verified:false },
  { id:'r30', destinationId:'d11', hotelId:null, userName:'Ahmed Khalil', avatar:'AK', rating:5, title:'Morocco is unforgettable', body:'The Sahara at night with zero light pollution — more stars than I have ever seen. The Medina of Fes is the most intact medieval city on earth. Moroccan hospitality is genuine and overwhelming.', date:'2024-10-30', helpful:123, verified:false },
  { id:'r31', destinationId:'d3', hotelId:null, userName:'Lucy Hawkins', avatar:'LH', rating:5, title:'Machu Picchu via train is still incredible', body:'Did the Vistadome train from Cusco instead of trekking due to time. Still breathtaking. The site itself at sunrise, before the day tours arrive, is genuinely mystical. Get there on the first bus at 5:30am.', date:'2024-10-12', helpful:145, verified:false },
  { id:'r32', destinationId:'d8', hotelId:null, userName:'Jake Morrison', avatar:'JM', rating:5, title:'Patagonia is the edge of the world', body:'The winds here are a character — they will literally blow you sideways. The Torres del Paine granite towers emerge from mist with cinematic drama. Grey Glacier calves ice into the lake. Nothing else in the world looks like this.', date:'2024-01-28', helpful:76, verified:false },
  { id:'r33', destinationId:'d10', hotelId:null, userName:'Grace Kim', avatar:'GK', rating:5, title:'Queenstown for adventure seekers', body:"Did the highest bungee in NZ, paragliding over the Remarkables, and white water rafting in Shotover Canyon in three days. Milford Sound on day four was the perfect contrast: silent, misty, Jurassic. New Zealand is extraordinary.", date:'2024-03-25', helpful:154, verified:false },
  { id:'r34', destinationId:'d13', hotelId:null, userName:'Sam Park', avatar:'SP', rating:4, title:'Bangkok for food lovers', body:'I ate from street stalls for a week and had better food than in Michelin-starred restaurants. Pad kra pao at 7am, mango sticky rice at noon, boat noodles from a floating vendor, green papaya salad at midnight. Heaven.', date:'2024-10-18', helpful:112, verified:false },
  { id:'r35', destinationId:'d14', hotelId:null, userName:'Elena Popescu', avatar:'EP', rating:5, title:'Dubrovnik: Game of Thrones made real', body:'Filming location aside, Dubrovnik is extraordinary on its own terms. The city walls at dawn with the Adriatic below, kayaking around the fortifications, the freshest seafood in the restaurant by the old port.', date:'2024-08-02', helpful:87, verified:false },
  { id:'r36', destinationId:'d15', hotelId:null, userName:'Chris Taylor', avatar:'CT', rating:4, title:'NYC in December is magical', body:'Central Park in snow, ice skating at Rockefeller Center, Midtown lit up for Christmas, oysters at Grand Central Oyster Bar. Yes it is expensive and chaotic. It is also the most alive place on earth.', date:'2024-12-15', helpful:98, verified:false },
  { id:'r37', destinationId:'d16', hotelId:null, userName:'Yemi Adeyemi', avatar:'YA', rating:5, title:"Cape Town — Africa's finest city", body:"Table Mountain hike via Platteklip Gorge took 2 hours and delivered views that made me understand why people love this city. The V&A Waterfront, Constantia wine farms, Bo-Kaap coloured houses — Cape Town is endlessly photogenic.", date:'2024-04-18', helpful:134, verified:false },
  { id:'r38', destinationId:'d17', hotelId:null, userName:'Lily Chen', avatar:'LC', rating:4, title:'Phuket island hopping is fantastic', body:'The longtail boat to Phi Phi Don, snorkeling in Maya Bay, swimming in the Emerald Cave by torchlight, back for sunset cocktails at the beach club — perfect day. Avoid peak Xmas/NYE unless you enjoy crowds.', date:'2024-05-30', helpful:65, verified:false },
  { id:'r39', destinationId:'d19', hotelId:null, userName:'Diego Souza', avatar:'DS', rating:4, title:'Rio beyond the clichés', body:'Lapa Arches at night — samba music pouring from every bar, locals and tourists dancing on the street. Santa Teresa neighbourhood with its bohemian galleries and trams. Pão de Açúcar. Cristo. The beaches. Rio has infinite depth.', date:'2024-03-08', helpful:89, verified:false },
  { id:'r40', destinationId:'d20', hotelId:null, userName:'Nadia El-Amin', avatar:'NA', rating:5, title:'Petra by candlelight is unforgettable', body:'We did Petra by Night — 1,500 candles lighting the Siq all the way to the Treasury, Bedouin musicians playing under a sky full of stars. Then walked back through the darkness in silence. One of the most powerful evenings of my life.', date:'2024-08-22', helpful:167, verified:false },
  { id:'r41', destinationId:'d1', hotelId:'h1', userName:'Hannah Brooks', avatar:'HB', rating:4, title:'Stunning but book well in advance', body:'Everything about Santorini is gorgeous but the island gets very crowded in July and August. The caldera hotels book out 12+ months ahead. Our sunset cruise was one of the highlights — highly recommend the catamaran tour.', date:'2024-08-12', helpful:76, verified:true },
  { id:'r42', destinationId:'d2', hotelId:'h2', userName:'Yuki Tanaka', avatar:'YT', rating:5, title:'Kyoto is timeless', body:'I have visited Kyoto four times and it reveals something new every visit. The Machiya Inn felt like staying in a living museum. Night walks through Gion sometimes reward you with glimpsed geiko. The morning tofu breakfast was delicate perfection.', date:'2024-11-07', helpful:103, verified:true },
  { id:'r43', destinationId:'d4', hotelId:'h4', userName:'Robert Walsh', avatar:'RW', rating:5, title:'Conrad Maldives is the benchmark', body:'Having now stayed at various luxury resorts across Asia, Conrad Rangali remains the gold standard. The underwater restaurant Ithaa is genuinely special. Our butler knew our preferences by day two.', date:'2024-09-24', helpful:178, verified:true },
  { id:'r44', destinationId:'d6', hotelId:'h6', userName:'Jennifer Adams', avatar:'JA', rating:5, title:'Four Seasons Serengeti: flawless', body:'This lodge sits on the rim of a watering hole. I watched elephants, giraffes, and zebras from the infinity pool. Our game drives were led by a naturalist with 20 years of Serengeti experience. The balloon safari at dawn was money well spent.', date:'2024-09-07', helpful:156, verified:true },
  { id:'r45', destinationId:'d18', hotelId:'h18', userName:'Claudia Müller', avatar:'CM', rating:5, title:"Andermatt is Switzerland's best kept secret", body:'Smaller and less crowded than Verbier or Zermatt, with better snow reliability. Chedi Hotel is architecturally fascinating — Asian minimalism in an alpine village. The 35m heated pool is extraordinary.', date:'2024-02-22', helpful:92, verified:true },
  { id:'r46', destinationId:'d11', hotelId:'h11', userName:'Arash Tehrani', avatar:'AT', rating:5, title:'La Mamounia lives up to legend', body:'Churchill painted here. Hitchcock filmed here. The garden alone is worth visiting Marrakech for. The spa uses traditional hammam techniques that leave your skin transformed. The Rose Garden restaurant serves the finest bastilla I have ever tasted.', date:'2024-11-01', helpful:134, verified:true },
  { id:'r47', destinationId:'d9', hotelId:'h9', userName:'Miriam Kowalski', avatar:'MK', rating:4, title:'Augustine Hotel is magnificent', body:'A 13th-century Augustinian monastery converted with extraordinary sensitivity. The vaulted ceilings, the inner courtyard, the library bar — deeply atmospheric. Walking to the Charles Bridge takes 5 minutes.', date:'2024-09-12', helpful:78, verified:true },
  { id:'r48', destinationId:'d3', hotelId:'h3', userName:'Carlos Mendez', avatar:'CM2', rating:5, title:'Inkaterra is the perfect base', body:'Staying at Inkaterra and walking to Machu Picchu gate in 20 minutes with no bus queues was the smart decision. The cloud forest ecosystem around the hotel is itself remarkable — hummingbirds at breakfast, orchids on the trails.', date:'2024-10-14', helpful:112, verified:true },
  { id:'r49', destinationId:'d12', hotelId:'h12', userName:'Ingrid Olsen', avatar:'IO', rating:5, title:'Ion Hotel makes Iceland perfect', body:'The design is striking — cantilevered over a lava field, large windows framing the landscape. The geothermal outdoor pool at midnight with Northern Lights overhead is the reason to visit in winter.', date:'2024-12-12', helpful:145, verified:true },
  { id:'r50', destinationId:'d7', hotelId:'h7', userName:'Daniel Kim', avatar:'DK', rating:5, title:'Alaya Ubud is extraordinary', body:'The rice terrace infinity pool at sunrise is one of the great hotel experiences on earth. Daily Balinese dance performances, organic cooking classes, expert spa treatments — Alaya does every element with genuine care. Ubud itself is deeply special.', date:'2024-11-18', helpful:167, verified:true },
];

// ── Storage helpers ──────────────────────────────────────────

const Storage = {
  get(key) { try { return JSON.parse(localStorage.getItem(key)); } catch { return null; } },
  set(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { return false; } },
  push(key, item) { const arr = this.get(key) || []; arr.push(item); return this.set(key, arr); },
  update(key, id, updates) {
    const arr = this.get(key) || [];
    const idx = arr.findIndex(i => i.id === id);
    if (idx === -1) return false;
    arr[idx] = { ...arr[idx], ...updates };
    return this.set(key, arr);
  },
  remove(key, id) { const arr = this.get(key) || []; return this.set(key, arr.filter(i => i.id !== id)); },
  find(key, id) { const arr = this.get(key) || []; return arr.find(i => i.id === id) || null; },
};

function initDB() {
  // v2 = INR prices — force re-seed if old data exists
  if (Storage.get(DB.initialized) === true) {
    Storage.set(DB.initialized, null);
  }
  if (Storage.get(DB.initialized) === 'v2') return;
  Storage.set(DB.destinations, SEED_DESTINATIONS);
  Storage.set(DB.hotels, SEED_HOTELS);
  Storage.set(DB.packages, SEED_PACKAGES);
  Storage.set(DB.reviews, SEED_REVIEWS);
  Storage.set(DB.bookings, Storage.get(DB.bookings) || []);
  Storage.set(DB.plans, Storage.get(DB.plans) || []);
  Storage.set(DB.initialized, 'v2');
}

function generateId(prefix = 'id') {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
}
